M48
; DRILL file {KiCad 7.0.9} date Thu Feb 15 22:09:57 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-15T22:09:57+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.24Y-2.62
X5.24Y-3.67
X6.78Y-2.62
X6.78Y-3.67
T0
M30
