M48
; DRILL file {KiCad 7.0.9} date Mon Jan  8 18:42:41 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-08T18:42:41+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.512Y-1.912
X4.512Y-3.812
X7.112Y-2.037
X7.112Y-3.687
T0
M30
