M48
; DRILL file {KiCad 7.0.9} date Mon Feb 26 23:44:48 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-26T23:44:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.9451Y-2.98
X5.24Y-2.23
X5.24Y-3.67
X6.78Y-2.23
X6.78Y-3.67
X7.1347Y-2.98
T0
M30
